# -*- coding: utf-8 -*-
"""お釣り計算機

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASVZ_DjB95izmPGiB_pSO1A0I7jHJoBE
"""

#お釣り計算機
money=int(input('現在の所持金額を入力してください>>'))
print(f'あなたの現在の所持金額は{money}円です。')
for m in range(3):
    goods=input('購入した商品の名前を入力してください>>')
    price=int(input(f'{goods}はいくらでしたか？'))
    money-=price
    if money<0:
      print('お金が足りません')
      break
    else:
      print(f'あなたの現在の所持金額は{money}円です。')