# -*- coding: utf-8 -*-
"""テスト順位判定

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YUdJPR8KMj_0uj6F94JAfgbSIdmoW_K
"""

#テスト順位判定
scores=[]
number=1
count=0
for n in range(5):
  score=int(input(f'{number}人目の得点を入力してください>>'))
  scores.append(score)
  number+=1
average=sum(scores)/len(scores)
max_score=max(scores)
min_score=min(scores)
for score in scores:
  if score>=average:
    count+=1
print(f'平均点は{average}点です。')
print(f'最高得点は{max_score}点です。')
print(f'最低点数は{min_score}点です。')
print(f'平均点以上の人数は{count}人です。')