# -*- coding: utf-8 -*-
"""会員登録システム

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSEibRDyN-mZ-gVRhXV2atqElzf4TwBJ
"""

#会員登録システム
user_names=[]
count=1
for u in range(3):
  user_name=input(f'登録する{count}人目のユーザーの名前を入力してください>>')
  user_names.append(user_name)
  count+=1
name=input('ログインする名前を入力してください>>')
if name in user_names:
  print('ログイン成功です。')
else:
  print('そのユーザーは登録されていません。')