# -*- coding: utf-8 -*-
"""偶数･奇数判定

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YUdJPR8KMj_0uj6F94JAfgbSIdmoW_K
"""

#偶数･奇数判定
for s in range(5):
  seisuu=int(input('数字を整数で入力してください>>'))
  if seisuu%2==0:
    print(f'{seisuu}は偶数です')
  else:
    print(f'{seisuu}は奇数です')