# -*- coding: utf-8 -*-
"""映画館のチケット料金計算機

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHI9z4A_VyuXRpzzxABRtaozk7tWIFiB
"""

#映画館のチケット料金計算機
adult_price=1800
kid_price=1000
adult_age=12
age=int(input('あなたの年齢を入力してください>>'))
if age>=adult_age:
  night_theater=input('夜間上映ですか？「y」か「n」で答えてください>>')
  if night_theater=='y':
    adult_price=adult_price-400
    print(f'{adult_price}円お支払いしてください。')
  else:
    print(f'{adult_price}円お支払いしてください。')
else:
  print(f'{kid_price}円お支払いしてください。')