# -*- coding: utf-8 -*-
"""買い物リスト管理

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSEibRDyN-mZ-gVRhXV2atqElzf4TwBJ
"""

#買い物リスト管理
goods_list=[]
for s in range(5):
  goods=input('買いたいものを入力してください>>')
  goods_list.append(goods)
print('買い物リスト')
print('1.'+goods_list[0])
print('2.'+goods_list[1])
print('3.'+goods_list[2])
print('4.'+goods_list[3])
print('5.'+goods_list[4]) #もっと簡単にできる？