# -*- coding: utf-8 -*-
"""銀行口座シミュレーター

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASVZ_DjB95izmPGiB_pSO1A0I7jHJoBE
"""

#銀行口座シミュレーター
print('あなたの入金,出金を管理します。')
zandaka=int(input('現在の口座残高を入力してください>>'))
print(f'あなたの現在の口座残高は{zandaka}円です。')
for z in range(5):
  choice=input('入金なら「1」を，出金なら「2」を入力してください>>')
  if choice=='1':
    nyuukinn=int(input('入金する金額を入力してください>>'))
    zandaka+=nyuukinn
    print(f'あなたの現在の口座残高は{zandaka}円です。')
  elif choice=='2':
    syukkinn=int(input('出金する金額を入力してください>>'))
    zandaka-=syukkinn
    if zandaka>=0:
      print(f'あなたの現在の口座残高は{zandaka}円です')
    else:
      print('お金が足りません')
      break